receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  # Jaeger all-in-one OTLP'yi dinliyor (4317). Güvenli değil/insecure:false gerekiyorsa true yapıyoruz.
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  logging:
    loglevel: info

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, logging]